// client/app/pages/hosting/mail.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { Mail, Shield, Smartphone, RefreshCw, Lock, CheckCircle2, ArrowRight } from 'lucide-vue-next'
import Box from '@/components/ui/layout/Box.vue'
import Flex from '@/components/ui/layout/Flex.vue'
import Grid from '@/components/ui/layout/Grid.vue'
import Section from '@/components/ui/layout/Section.vue'
import Container from '@/components/ui/layout/Container.vue'
import Heading from '@/components/ui/typography/Heading.vue'
import Text from '@/components/ui/typography/Text.vue'
import { Button } from '@/components/ui/button'

import PricingPlanRow from '@/components/PricingPlanRow.vue'
import FeatureCard from '@/components/FeatureCard.vue'
import FaqSection from '@/components/FaqSection.vue'
import CtaBanner from '@/components/CtaBanner.vue'

useHead({ title: 'Mail Hosting - HostiHub Premium' })

const plans = [
  {
    name: 'Starter Mail',
    specs: ['5 E-posta Hesabı', '10 GB Alan', 'Antispam Koruması', 'Webmail'],
    price: '40₺/ay'
  },
  {
    name: 'Pro Mail',
    specs: ['25 E-posta Hesabı', '50 GB Alan', 'Antispam Koruması', 'Webmail'],
    price: '80₺/ay'
  },
  {
    name: 'Business Mail',
    specs: ['Sınırsız E-posta', '100 GB Alan', 'Antispam Koruması', 'Webmail'],
    price: '150₺/ay'
  }
]

const features = [
  { title: 'Premium Antispam', description: 'Gelişmiş yapay zeka destekli filtreleme ile spam ve virüsleri gelen kutunuza ulaşmadan durdurun.', icon: Shield },
  { title: 'Mobil Uyumlu', description: 'IMAP/POP3/SMTP desteği ile e-postalarınıza telefon, tablet veya bilgisayarınızdan anında erişin.', icon: Smartphone },
  { title: 'Webmail Arayüzü', description: 'Modern ve hızlı Roundcube arayüzü ile dünyanın her yerinden maillerinizi yönetin.', icon: Mail },
  { title: 'Tam Güvenlik', description: 'TLS/SSL şifreleme standartları ile kurumsal iletişiminiz her zaman güvende ve gizli.', icon: Lock },
  { title: 'Kesintisiz İletişim', description: '%99.9 uptime garantisi ile e-posta trafiğiniz hiçbir zaman kesintiye uğramasın.', icon: CheckCircle2 },
  { title: 'Otomatik Yedekleme', description: 'E-postalarınız günlük olarak yedeklenir. Olası bir veri kaybında anında geri yükleme yapın.', icon: RefreshCw }
]

const faqs = [
  { question: 'Kendi alan adımla (isim@sirketim.com) e-posta kullanabilir miyim?', answer: 'Evet, sahip olduğunuz herhangi bir alan adı ile kurumsal e-posta adresleri oluşturabilir ve profesyonel bir görünüm elde edebilirsiniz.' },
  { question: 'E-postalarımı telefonumdan okuyabilir miyim?', answer: 'Kesinlikle. Tüm mail hosting paketlerimiz IMAP ve POP3 protokollerini destekler. iOS Mail, Gmail, Outlook gibi tüm mobil uygulamalarla tam uyumludur.' },
  { question: 'Eski firmamdaki e-postaları size taşıyabilir miyim?', answer: 'Evet, uzman teknik ekibimiz eski sunucunuzdaki tüm maillerinizi hiçbir veri kaybı yaşamadan ücretsiz olarak yeni sunucularımıza taşımaktadır.' },
  { question: 'Spam koruması nasıl çalışıyor?', answer: 'Sunucularımızda bulunan gelişmiş SpamAssassin ve yapay zeka destekli filtreler sayesinde spam maillerin %99\'u gelen kutunuza düşmeden engellenir.' }
]

// Intersection Observer for scroll reveal
const observerRef = ref<IntersectionObserver | null>(null)

onMounted(() => {
  observerRef.value = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add('is-visible')
        }
      })
    },
    { threshold: 0.1, rootMargin: '0px 0px -50px 0px' }
  )

  document.querySelectorAll('.reveal-on-scroll').forEach((el) => {
    observerRef.value?.observe(el)
  })
})

onUnmounted(() => {
  observerRef.value?.disconnect()
})
</script>

<template>
  <Box>
    <!-- Hero Section -->
    <Flex as="section" align="center" justify="center" class="relative min-h-[70vh] grid-pattern overflow-hidden pt-20">
      <!-- Enhanced multi-layer glow background -->
      <Box class="hero-glow-enhanced absolute inset-0" />
      
      <!-- Decorative gradient orbs -->
      <Box class="absolute top-1/4 left-1/4 w-96 h-96 bg-white/[0.02] rounded-full blur-3xl animate-float pointer-events-none" />
      <Box class="absolute bottom-1/4 right-1/4 w-96 h-96 bg-white/[0.02] rounded-full blur-3xl animate-float pointer-events-none" style="animation-delay: -3s" />
      
      <Container size="md" class="relative z-10 text-center">
        <Flex direction="col" align="center" gap="8">
          <!-- Animated badge -->
          <Flex 
            align="center" 
            gap="2" 
            class="px-4 py-2 rounded-full border border-white/10 bg-white/[0.03] backdrop-blur-sm animate-in fade-in slide-in-from-bottom-4 duration-700"
          >
            <Mail class="w-4 h-4 text-white/60" />
            <Text size="sm" weight="medium" class="text-zinc-300">Kurumsal E-Posta Çözümleri</Text>
          </Flex>

          <Heading as="h1" size="h1" class="text-white leading-[1.1] animate-in fade-in slide-in-from-bottom-8 duration-1000 delay-150 fill-mode-both tracking-tight">
            İletişiminizi<br>güçlendirin
          </Heading>
          
          <Text size="lg" class="text-zinc-400 max-w-2xl animate-in fade-in slide-in-from-bottom-8 duration-1000 delay-300 fill-mode-both leading-relaxed">
            Spam içermeyen, yüksek güvenlikli ve kesintisiz kurumsal mail hosting hizmeti. 
            <span class="text-zinc-300">Profesyonel görünüm, mükemmel erişilebilirlik.</span>
          </Text>
        </Flex>
      </Container>

      <!-- Bottom gradient fade -->
      <Box class="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-black to-transparent pointer-events-none" />
    </Flex>

    <!-- Pricing Plans -->
    <Section padding="xl" class="relative z-10">
      <Container size="lg">
        <Flex direction="col" gap="4" class="max-w-4xl mx-auto reveal-on-scroll">
          <PricingPlanRow 
            v-for="plan in plans" 
            :key="plan.name" 
            v-bind="plan" 
          />
        </Flex>
      </Container>
    </Section>

    <!-- Gradient Separator -->
    <Box class="gradient-separator" />

    <!-- Features -->
    <Section variant="muted" padding="xl">
      <Container size="lg">
        <Flex direction="col" align="center" gap="16">
          <Flex direction="col" align="center" gap="4" class="text-center max-w-2xl reveal-on-scroll">
            <Flex align="center" gap="2" class="px-3 py-1 rounded-full border border-white/10 bg-white/[0.03] mb-2">
              <Box class="w-2 h-2 rounded-full bg-white/40 animate-pulse" />
              <Text size="xs" weight="semibold" class="text-zinc-400 uppercase tracking-wider">Avantajlar</Text>
            </Flex>
            <Heading as="h2" size="h2" class="text-white">Neden Premium Mail?</Heading>
            <Text size="lg" variant="muted" class="leading-relaxed">Kurumsal iletişiminizin güvenliği ve devamlılığı için tasarlanmış özel altyapı.</Text>
          </Flex>

          <Grid cols="1" class="md:grid-cols-2 lg:grid-cols-3 gap-6 w-full">
            <FeatureCard 
              v-for="(f, index) in features" 
              :key="f.title" 
              v-bind="f" 
              :index="index"
            />
          </Grid>
        </Flex>
      </Container>
    </Section>

    <!-- Gradient Separator -->
    <Box class="gradient-separator" />

    <!-- FAQ -->
    <FaqSection :faqs="faqs" />

    <!-- CTA -->
    <CtaBanner 
      title="Kurumsal e-posta adresinizi hemen oluşturun!" 
      primary-text="Şimdi Başlayın" 
      primary-link="/auth/register" 
      secondary-text="Bize Ulaşın" 
      secondary-link="/contact" 
    />
  </Box>
</template>

// client/src/app/hosting/mail/page.tsx
'use client';

import { useState } from "react";
import { motion } from "framer-motion";
import { Check, Mail, Shield, ShieldCheck, MailOpen, Layers, Users, Server } from "lucide-react";
import Link from "next/link";
import dynamic from 'next/dynamic';
import { BackgroundEffects } from "@/components/BackgroundEffects";

const FaqSection = dynamic(() => import('@/components/FaqSection').then(mod => mod.FaqSection));
const Footer = dynamic(() => import('@/components/Footer').then(mod => mod.Footer));

export default function MailHostingPage() {

  const faqs = [
    {
      question: 'Kendi alan adım (domain) ile e-posta kullanabilir miyim?',
      answer: 'Kesinlikle. Sahip olduğunuz mevcut alan adınızı (örn: adiniz@sirketiniz.com) sistemlerimize bağlayarak dakikalar içinde profesyonel e-posta gönderip almaya başlayabilirsiniz.'
    },
    {
      question: 'Outlook veya akıllı telefonumdan e-postalarımı kontrol edebilir miyim?',
      answer: 'Tüm mail hosting sunucularımız POP3, IMAP ve SMTP protokollerini tam olarak destekler. Outlook, Apple Mail, Gmail uygulaması veya herhangi bir mobil cihazdan e-postalarınızı senkronize edebilirsiniz.'
    },
    {
      question: 'Anti-Spam (Gereksiz e-posta) koruması var mı?',
      answer: 'Evet, kurumsal mail sunucularımızda yapay zeka destekli gelişmiş Anti-Spam ve Anti-Virüs koruması bulunmaktadır. Gelen kutunuz gereksiz ve zararlı yazılımlardan %99 oranında temizlenir.'
    },
    {
      question: 'Eski maillerimi size taşıyabilir miyim?',
      answer: 'Taşıma uzmanlarımız, eski e-posta sunucunuzdaki veya standart hostinginizdeki tüm mailleri klasör yapıları bozulmadan yeni kurumsal mail servisine ücretsiz olarak taşımaktadır.'
    }
  ];

  const plans = [
    {
      name: "Kurumsal 10",
      desc: "Giriş seviyesi işletmeler ve startup'lar için.",
      price: { 'try': '39', 'usd': '1.2', 'eur': '1.1' },
      features: ['10 GB E-Posta Kotası', '5 Adet Mail Hesabı', 'Gelişmiş Anti-Spam', 'IMAP/POP3 Desteği', 'Mobil & Webmail Uyumlu']
    },
    {
      name: "Kurumsal 50",
      desc: "Yoğun mail trafiği olan orta ölçekli şirketler için.",
      price: { 'try': '79', 'usd': '2.5', 'eur': '2.3' },
      features: ['50 GB E-Posta Kotası', '25 Adet Mail Hesabı', 'Gelişmiş Anti-Spam', 'Ortak Takvim & Ajanda', 'Ücretsiz Mail Taşıma', 'Öncelikli Destek']
    },
    {
      name: "Kurumsal Limitsiz",
      desc: "Kurumsal büyük markalar ve ajanslar için.",
      price: { 'try': '149', 'usd': '4.5', 'eur': '4.2' },
      features: ['Limitsiz E-Posta Kotası', 'Limitsiz Mail Hesabı', 'Özel IP Adresi', 'Gelişmiş Anti-Spam', 'Ortak Takvim & Ajanda', 'Sınırsız Arşivleme']
    }
  ];


  return (
    <main className="flex-1 text-white min-h-screen">

      {/* Hero Section */}
      <section className="relative px-6 pb-20 pt-32 text-center flex flex-col items-center justify-center overflow-hidden">
        <BackgroundEffects />

        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="mx-auto mt-10 max-w-4xl select-none text-5xl font-medium leading-[1.05] tracking-tight lg:text-[72px] md:text-6xl"
        >
          Kurumsal <br /> Mail Hosting
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="mx-auto mt-8 max-w-2xl text-base text-white/60 font-normal leading-relaxed tracking-wide md:text-[17px]"
        >
          İşletmeniz için özel olarak tasarlanmış yüksek spam filtreli, hiçbir zaman çakılmayan premium e-posta barındırma hizmeti.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="relative z-20 mt-10 flex justify-center"
        >
        </motion.div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="container mx-auto px-6 pb-20 space-y-6 max-w-7xl">
        {/* Pricing Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 pt-8">
          {plans.map((plan, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: idx * 0.1 }}
              className="flex flex-col relative overflow-hidden rounded-xl bg-white/[0.01] border border-white/10 p-8 hover:bg-white/[0.02] transition-colors"
            >
              <div className="mb-6">
                <h3 className="text-2xl font-bold mb-2">{plan.name}</h3>
                <p className="text-sm text-white/50">{plan.desc}</p>
              </div>
              <div className="mb-8">
                <span className="text-4xl font-bold">₺{plan.price['try']}</span>
                <span className="text-white/50">/ay</span>
              </div>
              <ul className="space-y-4 mb-8 flex-1">
                {plan.features.map((feat, i) => (
                  <li key={i} className="flex items-center gap-3 text-sm text-white/80">
                    <Check className="w-5 h-5 text-white/40 shrink-0" />
                    <span>{feat}</span>
                  </li>
                ))}
              </ul>
              <Link href={`/checkout?plan=mail-${idx}`} className="block w-full py-3 text-center rounded-lg bg-white/5 hover:bg-white/10 text-white font-medium transition-all">
                Sipariş Ver
              </Link>
            </motion.div>
          ))}
        </div>
      </section>

      <div className="container mx-auto px-6 max-w-6xl pb-20">
        <FaqSection faqs={faqs} />
      </div>

      <Footer />
    </main>
  );
}
