// client/src/app/[locale]/panel/dashboard/page.tsx
'use client';

import { useTranslations } from 'next-intl';
import { Server, Receipt, Ticket, ArrowRight, CheckCircle2, Clock, Loader2, AlertCircle } from 'lucide-react';
import { Link } from '@/i18n/routing';
import { useEffect, useState } from 'react';
import { api, ApiError } from '@/lib/api';
import { useAuthStore } from '@/store/useAuthStore';

export default function DashboardPage() {
  const t = useTranslations('Panel.Dashboard');
  const user = useAuthStore(state => state.user);
  const [mounted, setMounted] = useState(false);
  
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    setMounted(true);
    const fetchData = async () => {
      try {
        const json = await api.get<{ stats: any; recentServices: any[]; recentInvoices: any[] }>('/dashboard/stats');
        setData(json);
      } catch (err: any) {
        console.error("Failed to fetch dashboard stats", err);
        setError(err.message || 'Failed to load dashboard data');
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  if (loading) {
    return (
      <div className="space-y-6 animate-pulse">
        <div className="h-24 bg-surface rounded-md border border-border"></div>
        <div className="h-[400px] bg-surface rounded-md border border-border"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="h-96 flex flex-col items-center justify-center text-center">
        <AlertCircle className="w-10 h-10 text-red-500 mb-4" />
        <h3 className="text-foreground font-medium mb-2">{t('error_occurred')}</h3>
        <p className="text-foreground-secondary">{error}</p>
      </div>
    );
  }

  const activeServices = data?.stats?.activeServices || 0;
  const unpaidInvoices = data?.stats?.unpaidInvoices || 0;
  const openTickets = data?.stats?.openTickets || 0;
  const balance = data?.stats?.balance || '0.00';
  const recentServices = data?.recentServices || [];

  return (
    <div className="space-y-12">
      {/* Account Hero */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 pb-8 border-b border-white/5">
        <div>
          <h1 className="text-[32px] font-semibold tracking-tight text-white mb-3">
            {t('greeting_evening')}{mounted && user?.name ? user.name.split(' ')[0] : t('customer')}.
          </h1>
          <div className="flex items-center gap-3 text-[14px] text-white/50">
            <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 backdrop-blur-md">
              <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.8)]"></div>
              <span className="text-[12px] text-white/80 font-medium tracking-wide uppercase">{t('systems_operational')}</span>
            </div>
            <span>•</span>
            <span className="tracking-wide">{t('you_have')} {activeServices} {t('active_services_count')}</span>
          </div>
        </div>
        
        <div className="flex items-center gap-10">
          <div className="flex flex-col">
            <span className="text-white/40 mb-1.5 uppercase tracking-widest text-[10px] font-bold">{t('account_balance')}</span>
            <span className="text-3xl font-semibold tracking-tight text-white">₺{balance}</span>
          </div>
          <div className="flex flex-col">
            <span className="text-white/40 mb-1.5 uppercase tracking-widest text-[10px] font-bold">{t('open_tickets_count')}</span>
            <span className="text-3xl font-semibold tracking-tight text-white">{openTickets}</span>
          </div>
          <div className="flex flex-col">
            <span className="text-white/40 mb-1.5 uppercase tracking-widest text-[10px] font-bold">{t('unpaid_invoices_count')}</span>
            <span className={`text-3xl font-semibold tracking-tight ${unpaidInvoices > 0 ? 'text-red-400' : 'text-white'}`}>{unpaidInvoices}</span>
          </div>
        </div>
      </div>

      {/* Services Section */}
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-medium text-white tracking-tight">{t('active_infrastructure')}</h2>
          <Link href="/panel/services" className="text-[14px] text-white/50 hover:text-white transition-colors flex items-center gap-1">
            {t('view_all_services')} <ArrowRight className="w-4 h-4" />
          </Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {recentServices.length > 0 ? (
            recentServices.map((service: any, i: number) => (
              <Link key={i} href={`/panel/services/${service.id}`} className="group relative overflow-hidden rounded-3xl bg-white/[0.02] border border-white/5 p-6 hover:bg-white/[0.04] transition-all duration-500 flex flex-col justify-between min-h-[160px] backdrop-blur-xl">
                <div className="absolute inset-0 bg-gradient-to-br from-white/[0.05] to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                
                <div className="flex items-start justify-between relative z-10">
                  <div className="flex flex-col gap-1">
                    <span className="text-[12px] font-semibold tracking-widest text-white/40 uppercase">
                      {service.type === 'vps' ? t('vps_server') : service.type === 'web' ? t('web_hosting') : service.type}
                    </span>
                    <h3 className="text-lg font-medium text-white tracking-tight">{service.name}</h3>
                  </div>
                  <div className={`px-2.5 py-1 rounded-full border text-[11px] font-bold tracking-wider uppercase ${service.status === 'active' ? 'bg-emerald-400/10 border-emerald-400/20 text-emerald-400' : 'bg-red-400/10 border-red-400/20 text-red-400'}`}>
                    {service.status}
                  </div>
                </div>

                <div className="flex items-center justify-between mt-6 relative z-10">
                  <div className="flex flex-col">
                    <span className="text-[11px] text-white/30 uppercase tracking-wider mb-1">IP Address</span>
                    <span className="text-[13px] text-white/70 font-mono">{service.ipAddress || t('not_assigned')}</span>
                  </div>
                  <div className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center group-hover:bg-white group-hover:text-black transition-all duration-300">
                    <ArrowRight className="w-4 h-4" />
                  </div>
                </div>
              </Link>
            ))
          ) : (
            <div className="col-span-full py-16 text-center rounded-3xl bg-white/[0.02] border border-white/5 flex flex-col items-center justify-center">
              <Server className="w-12 h-12 text-white/20 mb-4" />
              <p className="text-white/50 text-[15px]">{t('no_infrastructure')}</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// client/app/pages/dashboard/index.vue
<template>
  <div>
    <div class="mb-8">
      <h1 class="text-3xl font-bold text-white mb-2">Hoş Geldin, {{ authStore.userName }}</h1>
      <p class="text-zinc-400">Hosting hizmetlerinizin genel durumu ve hesap özetiniz.</p>
    </div>

    <!-- Stats -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
      <div class="bg-zinc-900/50 border border-white/5 rounded-2xl p-6 relative overflow-hidden group hover:border-white/10 transition-colors">
        <div class="absolute inset-0 bg-gradient-to-br from-white/[0.02] to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
        <div class="relative z-10">
          <div class="flex items-center justify-between mb-4">
            <span class="text-sm font-medium text-zinc-400">Aktif Hizmetler</span>
            <Server class="w-5 h-5 text-zinc-500" />
          </div>
          <p class="text-3xl font-bold text-white">{{ stats.services }}</p>
        </div>
      </div>
      <div class="bg-zinc-900/50 border border-white/5 rounded-2xl p-6 relative overflow-hidden group hover:border-white/10 transition-colors">
        <div class="absolute inset-0 bg-gradient-to-br from-white/[0.02] to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
        <div class="relative z-10">
          <div class="flex items-center justify-between mb-4">
            <span class="text-sm font-medium text-zinc-400">Ödenmemiş Faturalar</span>
            <CreditCard class="w-5 h-5 text-zinc-500" />
          </div>
          <p class="text-3xl font-bold text-white">{{ stats.unpaid }}</p>
        </div>
      </div>
      <div class="bg-zinc-900/50 border border-white/5 rounded-2xl p-6 relative overflow-hidden group hover:border-white/10 transition-colors">
        <div class="absolute inset-0 bg-gradient-to-br from-white/[0.02] to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
        <div class="relative z-10">
          <div class="flex items-center justify-between mb-4">
            <span class="text-sm font-medium text-zinc-400">Açık Talepler</span>
            <HeadphonesIcon class="w-5 h-5 text-zinc-500" />
          </div>
          <p class="text-3xl font-bold text-white">{{ stats.tickets }}</p>
        </div>
      </div>
    </div>

    <!-- Quick Actions & Recent Services -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
      <div class="lg:col-span-2">
        <h2 class="text-xl font-bold text-white mb-4">Son Alınan Hizmetler</h2>
        <div v-if="pending" class="flex justify-center p-8">
          <Loader2 class="w-6 h-6 animate-spin text-zinc-500" />
        </div>
        <div v-else-if="services.length === 0" class="bg-zinc-900/30 border border-white/5 rounded-2xl p-8 text-center">
          <Globe class="w-12 h-12 text-zinc-600 mx-auto mb-4" />
          <h3 class="text-lg font-medium text-white mb-2">Henüz bir hizmetiniz yok</h3>
          <p class="text-sm text-zinc-400 mb-6">Hemen yeni bir VDS veya Web Hosting satın alarak başlayın.</p>
          <NuxtLink to="/pricing" class="inline-flex items-center gap-2 bg-white text-black px-6 py-2.5 rounded-xl text-sm font-medium hover:bg-zinc-200 transition-colors">
            Hizmet Satın Al
          </NuxtLink>
        </div>
        <div v-else class="bg-zinc-900/50 border border-white/5 rounded-2xl overflow-hidden">
          <table class="w-full text-left border-collapse">
            <thead>
              <tr class="border-b border-white/5 text-sm text-zinc-500 bg-black/20">
                <th class="p-4 font-medium">Hizmet Adı</th>
                <th class="p-4 font-medium">Türü</th>
                <th class="p-4 font-medium">Durum</th>
                <th class="p-4 font-medium">İşlem</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="service in services.slice(0, 5)" :key="service.id" class="border-b border-white/5 last:border-0 hover:bg-white/[0.02] transition-colors">
                <td class="p-4">
                  <p class="font-medium text-white">{{ service.name }}</p>
                  <p class="text-xs text-zinc-500">{{ service.ipAddress || 'IP Atanmadı' }}</p>
                </td>
                <td class="p-4">
                  <span class="inline-flex items-center px-2 py-1 rounded-md bg-white/5 text-xs font-medium text-zinc-300 uppercase tracking-wider">
                    {{ service.type }}
                  </span>
                </td>
                <td class="p-4">
                  <div class="flex items-center gap-2">
                    <div class="w-2 h-2 rounded-full" :class="service.status === 'active' ? 'bg-green-500' : 'bg-yellow-500'"></div>
                    <span class="text-sm text-zinc-300 capitalize">{{ service.status }}</span>
                  </div>
                </td>
                <td class="p-4">
                  <NuxtLink :to="`/dashboard/service/${service.id}`" class="text-sm font-medium text-white hover:text-zinc-300 transition-colors">
                    Yönet →
                  </NuxtLink>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      
      <div>
        <h2 class="text-xl font-bold text-white mb-4">Hızlı İşlemler</h2>
        <div class="grid gap-4">
          <NuxtLink to="/pricing" class="group flex items-center gap-4 bg-zinc-900/50 border border-white/5 p-4 rounded-2xl hover:border-white/10 transition-colors">
            <div class="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center text-zinc-300 group-hover:bg-white group-hover:text-black transition-colors">
              <Plus class="w-5 h-5" />
            </div>
            <div>
              <p class="font-medium text-white text-sm">Yeni Sipariş Ver</p>
              <p class="text-xs text-zinc-500">VDS, Dedicated veya Web Hosting</p>
            </div>
          </NuxtLink>
          <NuxtLink to="/contact" class="group flex items-center gap-4 bg-zinc-900/50 border border-white/5 p-4 rounded-2xl hover:border-white/10 transition-colors">
            <div class="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center text-zinc-300 group-hover:bg-white group-hover:text-black transition-colors">
              <HeadphonesIcon class="w-5 h-5" />
            </div>
            <div>
              <p class="font-medium text-white text-sm">Destek Talebi</p>
              <p class="text-xs text-zinc-500">Yardıma mı ihtiyacınız var?</p>
            </div>
          </NuxtLink>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Server, CreditCard, HeadphonesIcon, Globe, Loader2, Plus } from 'lucide-vue-next'
import { useAuthStore } from '~/stores/auth'

definePageMeta({
  layout: 'dashboard',
  middleware: 'auth'
})

const authStore = useAuthStore()
const api = useApi()

const pending = ref(true)
const services = ref<any[]>([])

const stats = reactive({
  services: 0,
  unpaid: 0,
  tickets: 0
})

onMounted(async () => {
  try {
    const data = await api<{ services: any[] }>('/services')
    services.value = data.services || []
    stats.services = services.value.length
  } catch (e) {
    console.error(e)
  } finally {
    pending.value = false
  }
})
</script>
