// client/src/components/ReferenceBar.tsx
'use client'

import { motion } from "framer-motion";

interface Reference {
  name: string;
  count: string;
}

const references: Reference[] = [
  { name: 'Mutlu Müşteri', count: '10K+' },
  { name: 'Aktif Sunucu', count: '50K+' },
  { name: 'Uptime', count: '%99.9' },
  { name: 'Destek', count: '7/24' }
];

export function ReferenceBar() {
  return (
    <div className="relative z-10 w-full bg-white/[0.01] border-y border-white/10">
      <div className="max-w-7xl mx-auto">
        <div className="grid grid-cols-2 lg:grid-cols-4">
          {references.map((ref, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ duration: 0.5, delay: index * 0.1, ease: "easeOut" }}
              className={`group relative flex flex-col items-center justify-center text-center py-8 sm:py-12 md:py-16 px-4 sm:px-6 md:px-8 border-b border-white/10 lg:border-b-0 ${
                index !== references.length - 1 ? 'lg:border-r lg:border-white/10' : ''
              } ${
                index % 2 !== 1 ? 'border-r border-white/10 lg:border-r-0' : ''
              } ${
                index >= 2 ? 'max-sm:border-b-0' : ''
              }`}
            >
              <div 
                className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none"
                style={{ background: 'radial-gradient(circle at center, rgba(100,107,242,0.1) 0%, transparent 60%)' }}
              />

              <div className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold tracking-tighter text-white mb-1 sm:mb-2 relative z-10 group-hover:text-primary transition-colors duration-300">
                {ref.count}
              </div>
              <div className="text-sm font-medium text-foreground/60 uppercase tracking-widest relative z-10 group-hover:text-foreground/90 transition-colors duration-300">
                {ref.name}
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}

// client/app/components/ReferenceBar.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import Box from '@/components/ui/layout/Box.vue'
import Container from '@/components/ui/layout/Container.vue'
import Flex from '@/components/ui/layout/Flex.vue'
import Grid from '@/components/ui/layout/Grid.vue'
import Text from '@/components/ui/typography/Text.vue'

interface Reference {
  name: string
  count: string
}

interface Props {
  references: Reference[]
}

defineProps<Props>()

// Animated counter
const isVisible = ref(false)

onMounted(() => {
  const observer = new IntersectionObserver(
    (entries) => {
      if (entries[0].isIntersecting) {
        isVisible.value = true
        observer.disconnect()
      }
    },
    { threshold: 0.3 }
  )

  const el = document.querySelector('.stats-bar')
  if (el) observer.observe(el)
})
</script>

<template>
  <Box class="stats-bar py-16 bg-black/50 backdrop-blur-sm relative">
    <!-- Top subtle line -->
    <Box class="absolute top-0 left-0 right-0 h-px bg-white/5" />
    
    <Container size="lg">
      <Grid class="grid-cols-2 md:grid-cols-4 gap-8 md:gap-12">
        <Flex 
          v-for="(ref, index) in references" 
          :key="index"
          direction="col"
          align="center"
          justify="center"
          gap="3"
          class="text-center group"
          :class="{ 'animate-count-up': isVisible }"
          :style="{ animationDelay: `${index * 150}ms` }"
        >
          <!-- Value - white, clean -->
          <Text class="text-4xl md:text-5xl font-bold text-white tracking-tighter">
            {{ ref.count }}
          </Text>
          
          <!-- Label -->
          <Text class="text-sm font-medium text-zinc-500 uppercase tracking-widest group-hover:text-zinc-400 transition-colors duration-300">
            {{ ref.name }}
          </Text>
        </Flex>
      </Grid>
    </Container>

    <!-- Bottom subtle line -->
    <Box class="absolute bottom-0 left-0 right-0 h-px bg-white/5" />
  </Box>
</template>
