// client/app/components/CtaBanner.vue
<script setup lang="ts">
import { ArrowRight } from 'lucide-vue-next'
import Section from '@/components/ui/layout/Section.vue'
import Container from '@/components/ui/layout/Container.vue'
import Flex from '@/components/ui/layout/Flex.vue'
import Box from '@/components/ui/layout/Box.vue'
import Heading from '@/components/ui/typography/Heading.vue'
import Text from '@/components/ui/typography/Text.vue'
import { Button } from '@/components/ui/button'

interface Props {
  title: string
  primaryText: string
  primaryLink: string
  secondaryText?: string
  secondaryLink?: string
}

defineProps<Props>()
</script>

<template>
  <Section padding="xl" class="text-center section-glow relative overflow-hidden">
    <Box class="hero-glow absolute inset-0 -z-10 opacity-60" />

    <Container size="md" class="relative z-10">
      <Flex direction="col" align="center" gap="10" class="reveal-on-scroll">
        <Heading as="h2" size="h1" class="text-white tracking-tight leading-tight max-w-3xl">
          {{ title }}
        </Heading>
        
        <Flex direction="col" class="sm:flex-row items-center gap-5">
          <Button size="lg" asChild class="px-8 h-12 text-base font-medium shadow-lg shadow-white/10 hover:scale-[1.03] transition-all duration-300">
            <NuxtLink :to="primaryLink">
              {{ primaryText }}
              <ArrowRight class="ml-2 w-4 h-4" />
            </NuxtLink>
          </Button>
          
          <Button v-if="secondaryText && secondaryLink" variant="ghost" size="lg" asChild class="text-zinc-400 hover:text-white transition-all duration-300">
            <NuxtLink :to="secondaryLink">
              {{ secondaryText }}
            </NuxtLink>
          </Button>
        </Flex>
      </Flex>
    </Container>
  </Section>
</template>

// client/src/components/CtaBanner.tsx
'use client'

import { Link } from "@/i18n/routing";
import { motion } from "framer-motion";

interface Props {
  title: string;
  description?: string;
  primaryText: string;
  primaryLink: string;
  secondaryText?: string;
  secondaryLink?: string;
}

export function CtaBanner({ title, description, primaryText, primaryLink, secondaryText, secondaryLink }: Props) {
  return (
    <section className="relative z-10 overflow-hidden bg-background py-24 sm:py-32 border-t border-white/5">
      <div className="relative z-20 mx-auto max-w-4xl w-full px-6 text-center space-y-8">
        
        <motion.h2 
          initial={{ opacity: 0, y: 15 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.4 }}
          className="text-4xl md:text-5xl lg:text-6xl font-bold font-heading text-white tracking-tight leading-tight"
        >
          {title}
        </motion.h2>
        
        {description && (
          <motion.p 
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.4, delay: 0.1 }}
            className="text-[16px] md:text-[18px] text-foreground-secondary max-w-2xl mx-auto leading-relaxed"
          >
            {description}
          </motion.p>
        )}
        
        <motion.div 
          initial={{ opacity: 0, y: 15 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.4, delay: 0.2 }}
          className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4 w-full sm:w-auto"
        >
          <Link 
            href={primaryLink}
            className="rounded-lg px-8 py-3.5 bg-white text-black text-[15px] font-semibold hover:bg-white/90 active:scale-[0.98] transition-all duration-200 w-full sm:w-auto text-center shadow-sm"
          >
            {primaryText}
          </Link>
          
          {secondaryText && secondaryLink && (
            <Link 
              href={secondaryLink}
              className="rounded-lg px-8 py-3.5 border border-white/10 hover:border-white/20 bg-white/5 text-[15px] text-white/90 hover:text-white font-medium hover:bg-white/10 active:scale-[0.98] transition-all duration-200 w-full sm:w-auto text-center"
            >
              {secondaryText}
            </Link>
          )}
        </motion.div>
        
      </div>
    </section>
  );
}
