// client/app/components/FaqSection.vue
<script setup lang="ts">
import { 
  Accordion, 
  AccordionContent, 
  AccordionItem, 
  AccordionTrigger 
} from '@/components/ui/accordion'
import Section from '@/components/ui/layout/Section.vue'
import Container from '@/components/ui/layout/Container.vue'
import Grid from '@/components/ui/layout/Grid.vue'
import Box from '@/components/ui/layout/Box.vue'
import Heading from '@/components/ui/typography/Heading.vue'
import Text from '@/components/ui/typography/Text.vue'

interface Faq {
  question: string
  answer: string
}

interface Props {
  faqs: Faq[]
}

defineProps<Props>()
</script>

<template>
  <Section class="border-t border-white/5 bg-black" padding="xl">
    <Container size="lg">
      <Grid cols="1" class="lg:grid-cols-5 gap-12">
        <Box class="lg:col-span-2">
          <Heading as="h2" size="h2" class="text-white whitespace-pre-line leading-tight">
            Sıkça<br>sorulan<br>sorular.
          </Heading>
        </Box>
        <Box class="lg:col-span-3">
          <Accordion type="single" class="w-full space-y-4" collapsible>
            <AccordionItem 
              v-for="(faq, index) in faqs" 
              :key="index" 
              :value="`item-${index}`"
              class="border border-white/10 rounded-xl bg-white/[0.02] px-6 transition-colors hover:bg-white/[0.04]"
            >
              <AccordionTrigger class="text-lg font-medium text-white hover:no-underline hover:text-white/80 py-6">
                {{ faq.question }}
              </AccordionTrigger>
              <AccordionContent class="text-zinc-400 leading-relaxed pb-6 text-base">
                {{ faq.answer }}
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </Box>
      </Grid>
    </Container>
  </Section>
</template>

// client/src/components/FaqSection.tsx
'use client'

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Plus } from "lucide-react";
import { Flex, Grid, Container, Section, Heading, Text } from "@/components/ui";

interface Faq {
  question: string;
  answer: string;
}

interface Props {
  faqs: Faq[];
}

function FaqItem({ faq, isOpen, onClick }: { faq: Faq, isOpen: boolean, onClick: () => void }) {
  return (
    <div className="border-b border-white/10 last:border-0 group cursor-pointer" onClick={onClick}>
      <Flex items="center" justify="between" className="py-6">
        <h3 className={`text-lg md:text-xl font-medium transition-colors duration-300 ${isOpen ? 'text-primary' : 'text-white group-hover:text-white/80'}`}>
          {faq.question}
        </h3>
        <Flex items="center" justify="center" className="flex-shrink-0 ml-4 relative w-8 h-8 rounded-full border border-white/10 group-hover:border-white/20 transition-colors bg-white/5">
          <motion.div
            animate={{ rotate: isOpen ? 45 : 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
          >
            <Plus className={`w-4 h-4 transition-colors ${isOpen ? 'text-primary' : 'text-white'}`} />
          </motion.div>
        </Flex>
      </Flex>
      
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <div className="pb-6 sm:pb-8 pr-4 sm:pr-12">
              <Text className="text-base md:text-[17px]">
                {faq.answer}
              </Text>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export function FaqSection({ faqs }: Props) {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <Section className="py-16 sm:py-24 md:py-32 relative bg-transparent z-10">
      <Container size="6xl">
        <Grid cols={1} className="lg:grid-cols-12 gap-8 sm:gap-10 lg:gap-24">
          
          <div className="lg:col-span-5">
            <div className="sticky top-32">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.7 }}
              >
                <div className="w-fit rounded-full bg-white/5 border border-white/10 px-4 py-1.5 text-xs font-medium tracking-wide mb-6">
                  Sıkça Sorulan Sorular
                </div>
                <Heading level={2} className="text-3xl sm:text-4xl md:text-5xl leading-[1.1] mb-4 sm:mb-6">
                  Aklınızda soru işareti kalmasın.
                </Heading>
                <Text className="text-base md:text-lg">
                  Platformumuz hakkında en çok merak edilen soruları ve cevapları sizin için derledik.
                </Text>
              </motion.div>
            </div>
          </div>
          
          <div className="lg:col-span-7">
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.7, delay: 0.2 }}
              className="flex flex-col border-t border-white/10"
            >
              {faqs.map((faq, index) => (
                <FaqItem 
                  key={index} 
                  faq={faq} 
                  isOpen={openIndex === index} 
                  onClick={() => setOpenIndex(openIndex === index ? null : index)} 
                />
              ))}
            </motion.div>
          </div>

        </Grid>
      </Container>
    </Section>
  );
}
